export const appRoutes = {
  mainTabNavigator: 'mainTabNavigator',
  authNavigator: 'authNavigator',
  homeStack: 'homeStack',
  walletStack: 'walletStack',
  accountStack: 'accountStack',
  exchangePointStack: 'exchangePointStack',
  giftStack: 'giftStack',
  homeScreen: 'homeScreen',
  foodDetailScreen: 'foodDetailScreen',
  chatScreen: 'chatScreen',
  walletScreen: 'walletScreen',
  loginScreen: 'loginScreen',
  registerScreen: 'registerScreen',
  accountScreen: 'accountScreen',
  addLoyalPointScreen: 'addLoyalPointScreen',
  bankScreen: 'bankScreen',
  partnerBrandScreen: 'partnerBrandScreen',
  historyScreen: 'historyScreen',
  exchangePointScreen: 'exchangePointScreen',
  vnpayScreen: 'vnpayScreen',
  transactionDetailScreen: 'transactionDetailScreen',
  brandProfileScreen: 'brandProfileScreen',
  voucherDetailScreen: 'voucherDetailScreen',
  giftScreen: 'giftScreen',
  userProfileScreen: 'userProfileScreen',
  userCodeScreen: 'userCodeScreen',
  requestEarnPointScreen: 'requestEarnPointScreen',
  scannerStack: 'scannerStack',
  scannerScreen: 'scannerScreen',
  voucherListScreen: 'voucherListScreen',
  searchScreen: 'searchScreen',
}

export const deepLinkRoutes = {
  all: 'all',
  point: 'point',
}
